---
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-paginate
- jekyll-admin
- jekyll-gist
twitter:
  username: randyzwitch
permalink: /:title
name: randyzwitch
url: http://randyzwitch.com
paginate: 3
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Randy Zwitch"
      layout: "responsive"
      author: "Randy Zwitch"
